# Generated by Django 4.1.5 on 2023-08-27 01:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(default=datetime.datetime.now)),
                ('action_time', models.TimeField(default=datetime.datetime.now)),
                ('action', models.CharField(max_length=255)),
                ('object_repr', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=90, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['id'],
                'permissions': (('view_activity_users', 'Can view Actividades de Usuarios'), ('delete_activity_users', 'Can delete Actividades de Usuarios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DetUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo Modificado')),
                ('previous_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Anterior')),
                ('current_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Actual')),
                ('user_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='det_user_activity_set', to='audit_log.useractivity', verbose_name='Actividad de Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['id'],
                'permissions': (('view_det_activity_users', 'Can view Detalle Actividades de Usuarios'), ('delete_det_activity_users', 'Can delete Detalle Actividades de Usuarios')),
                'default_permissions': (),
            },
        ),
    ]
