# Generated by Django 4.1.5 on 2023-05-10 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsalidainsumos',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='det_salidainsumos_set', to='erp.salidaproduc', verbose_name='Código distribución'),
        ),
        migrations.DeleteModel(
            name='SalidaInsumos',
        ),
    ]
