# Generated by Django 4.1.5 on 2023-06-14 23:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0003_alter_detsalidainsumos_salida_delete_salidainsumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Código')),
                ('estado', models.CharField(blank=True, choices=[('ECR', 'En Creación'), ('PEN', 'Pendiente'), ('REC', 'Rechazada'), ('RES', 'Resuelta')], default='ECR', max_length=3, null=True, verbose_name='Estado de la Solicitud')),
                ('prioridad', models.CharField(blank=True, choices=[('MB', 'Muy baja'), ('BJ', 'Baja'), ('NM', 'Normal'), ('AT', 'Alta'), ('MA', 'Muy alta')], max_length=2, null=True)),
                ('tipo_prod', models.CharField(blank=True, choices=[('BMU', 'Bien mueble en uso'), ('BMD', 'Bien en deposito')], max_length=3, null=True)),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Solicitud')),
                ('observ', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Ultima modificación')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_soporte_unidad', to='erp.unidad', verbose_name='Unidad Solicitante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_soporte_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio Técnico',
                'verbose_name_plural': 'Solicitudes de Servicio Técnico',
                'ordering': ['codigo'],
            },
        ),
    ]
