# Generated by Django 4.1.5 on 2023-06-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_solitudsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='solitudsoporte',
            name='motivo',
            field=models.CharField(blank=True, choices=[('REP', 'Reparacion de producto'), ('AST', 'Asesoramiento')], default='AST', max_length=3, null=True),
        ),
    ]
