# Generated by Django 4.1.5 on 2023-06-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_solitudsoporte_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetSolicSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observ', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodsolic_soport_set', to='erp.producto', verbose_name='Producto')),
                ('solic_soport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solic_soport_set', to='erp.solitudsoporte', verbose_name='Código de Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Desincorporación de Almacen',
                'verbose_name_plural': 'Detalle de Desincorporaciones de Almacen',
                'ordering': ['id'],
            },
        ),
    ]
