# Generated by Django 4.1.5 on 2023-06-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_detsolicsoporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detsolicsoporte',
            options={'ordering': ['id'], 'verbose_name': 'Detalle Solicitud de Servicio Técnico', 'verbose_name_plural': 'Detalle Solicitudes de Servicio Técnico'},
        ),
    ]
