# Generated by Django 4.1.5 on 2023-06-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_detsolicsoporte_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solitudsoporte',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='solitudsoporte',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetSolicSoporte',
        ),
        migrations.DeleteModel(
            name='SolitudSoporte',
        ),
    ]
