# Generated by Django 4.1.5 on 2023-06-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_lotes_fecha_venc'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriales',
            name='incorp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incorp_serial_set', to='erp.ingresoproduc'),
        ),
    ]
