# Generated by Django 4.1.5 on 2023-06-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_seriales_incorp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='incorp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incorp_lote_set', to='erp.ingresoproduc'),
        ),
    ]
