# Generated by Django 4.1.5 on 2023-06-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_lotes_incorp'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriales',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_serial_set', to='erp.producto'),
        ),
    ]
