# Generated by Django 4.1.5 on 2023-06-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_seriales_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriales',
            name='disp',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Disponibilidad'),
        ),
    ]
