# Generated by Django 4.1.5 on 2023-07-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_detsalidaprod_cant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dettrasladoprod',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='dettrasladoprod',
            name='subtotal',
        ),
    ]
