# Generated by Django 4.1.5 on 2023-07-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_remove_dettrasladoprod_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Producto'),
        ),
    ]
