# Generated by Django 4.1.5 on 2023-07-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_item',
        ),
    ]
