# Generated by Django 4.1.5 on 2023-08-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_concepmovimiento_salida_bienes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desincalmacen',
            name='estado',
            field=models.CharField(choices=[('DIS', 'En creación'), ('PAP', 'Por aprobar')], default='DIS', max_length=3, verbose_name='Estado desincorporación'),
        ),
        migrations.AlterField(
            model_name='desincproduc',
            name='estado',
            field=models.CharField(choices=[('DIS', 'En creación'), ('PAP', 'Por aprobar')], default='DIS', max_length=3, verbose_name='Estado desincorporación'),
        ),
        migrations.AlterField(
            model_name='ingresoproduc',
            name='estado',
            field=models.CharField(choices=[('DIS', 'En creación'), ('PAP', 'Por aprobar')], default='DIS', max_length=3, verbose_name='Estado ingreso'),
        ),
        migrations.AlterField(
            model_name='salidaproduc',
            name='estado',
            field=models.CharField(choices=[('DIS', 'En creación'), ('PAP', 'Por aprobar')], default='DIS', max_length=3, verbose_name='Estado distribución'),
        ),
        migrations.AlterField(
            model_name='trasladoproduc',
            name='estado',
            field=models.CharField(choices=[('DIS', 'En creación'), ('PAP', 'Por aprobar')], default='DIS', max_length=3, verbose_name='Estado Operación'),
        ),
    ]
