# Generated by Django 4.1.5 on 2023-08-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_alter_desincalmacen_estado_alter_desincproduc_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
