# Generated by Django 4.1.5 on 2023-08-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_producto_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='ced',
            new_name='cedula',
        ),
    ]
