# Generated by Django 4.1.5 on 2023-08-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_rename_ced_almacen_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codbienes',
            name='procedencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codbienes_unidad_central_set', to='erp.unidad', verbose_name='Unidad Admin. Central'),
        ),
        migrations.AlterField(
            model_name='codbienes',
            name='unidad_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codbienes_unidad_admin_set', to='erp.unidad', verbose_name='Unidad Admin. Local'),
        ),
    ]
