# Generated by Django 4.1.5 on 2023-09-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresoproduc',
            options={'ordering': ['id'], 'verbose_name': 'Incorporación', 'verbose_name_plural': 'Incorporaciones'},
        ),
    ]
