# Generated by Django 4.1.5 on 2023-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariobienes',
            name='ult_proc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ultimo Proceso'),
        ),
    ]
