# Generated by Django 4.1.5 on 2023-09-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_alter_inventariobienes_ult_proc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariobienes',
            name='ant_tipo_proc',
        ),
        migrations.RemoveField(
            model_name='inventariobienes',
            name='ant_ult_proc',
        ),
    ]
