# Generated by Django 4.1.5 on 2023-10-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_remove_producto_created_remove_producto_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='created',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='updated',
        ),
    ]
