# Generated by Django 4.1.5 on 2023-10-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_remove_moneda_created_remove_moneda_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='created',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='updated',
        ),
    ]
