# Generated by Django 4.1.5 on 2023-10-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_remove_almacen_created_remove_almacen_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepmovimiento',
            name='created',
        ),
        migrations.RemoveField(
            model_name='concepmovimiento',
            name='updated',
        ),
    ]
