# Generated by Django 4.1.5 on 2023-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_remove_departamento_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ced_repre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula representante'),
        ),
    ]
