# Generated by Django 4.1.5 on 2023-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_remove_codbienes_procedencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproduc',
            name='estado',
            field=models.CharField(choices=[('EN CREACIÓN', 'En creación'), ('POR APROBAR', 'Por aprobar')], default='EN CREACIÓN', max_length=25),
        ),
    ]
