# Generated by Django 4.1.5 on 2023-10-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_alter_ingresoproduc_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='updated',
        ),
    ]
