# Generated by Django 4.1.5 on 2023-11-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_alter_controlstock_almacenes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trasladoproduc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trasladoproduc',
            name='updated',
        ),
        migrations.AlterField(
            model_name='trasladoproduc',
            name='estado',
            field=models.CharField(choices=[('EN CREACIÓN', 'En creación'), ('POR APROBAR', 'Por aprobar')], default='POR APROBAR', max_length=25),
        ),
    ]
