# Generated by Django 4.1.5 on 2023-11-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_remove_trasladoproduc_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstock',
            name='apartados',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
