# Generated by Django 4.1.5 on 2023-11-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_controlstock_apartados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='multialmacen',
        ),
        migrations.AddField(
            model_name='empresa',
            name='almacen_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_almacen_set', to='erp.almacen'),
        ),
    ]
