# Generated by Django 4.1.5 on 2023-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_remove_empresa_estado_remove_empresa_multialmacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='solic_almacen',
            field=models.BooleanField(blank=True, default=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_unidad',
            field=models.CharField(blank=True, choices=[('UADMC', 'Unidad Administrativa Central'), ('UADML', 'Unidad Administrativa Local'), ('UASIC', 'Unidad ASIC')], max_length=25, null=True, verbose_name='Tipo de Unidad'),
        ),
    ]
