# Generated by Django 4.1.5 on 2023-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_mensaje_options_sala_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ('fecha',)},
        ),
        migrations.AlterField(
            model_name='sala',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
