# Generated by Django 4.1.5 on 2023-09-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_sala_options_alter_sala_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo_sala',
            field=models.CharField(blank=True, choices=[('PRIVADA', 'Privada'), ('PÚBLICA', 'Pública')], max_length=14, null=True),
        ),
    ]
