# Generated by Django 4.1.5 on 2023-09-29 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_mensaje_editado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
