# Generated by Django 4.1.5 on 2023-10-21 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_link', models.CharField(default='theme_blue', max_length=25)),
                ('sidebar_theme', models.CharField(default='sidebar-dark-primary', max_length=25)),
                ('brand_logo_theme', models.CharField(blank=True, max_length=25, null=True)),
                ('navbar_theme', models.CharField(default='theme_blue', max_length=25)),
                ('navbar_options', models.CharField(blank=True, max_length=25, null=True)),
                ('sidebar_collapse', models.CharField(blank=True, max_length=25, null=True)),
                ('sidebar_fixed', models.CharField(blank=True, max_length=25, null=True)),
                ('sidebar_flat', models.CharField(blank=True, max_length=25, null=True)),
                ('sidebar_vertical', models.CharField(blank=True, max_length=25, null=True)),
                ('sidebar_legacy', models.CharField(blank=True, max_length=25, null=True)),
                ('sidebar_disable_hover', models.CharField(blank=True, max_length=25, null=True)),
                ('small_body', models.CharField(blank=True, max_length=25, null=True)),
                ('small_navbar', models.CharField(blank=True, max_length=25, null=True)),
                ('small_brand', models.CharField(blank=True, max_length=25, null=True)),
                ('small_sidebar_nav', models.CharField(blank=True, max_length=25, null=True)),
                ('small_footer', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizer_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personalización de Interfaz',
                'verbose_name_plural': 'Personalizaciones de Interfaz',
                'ordering': ['id'],
                'permissions': (('advanced_customizations', 'Can change advanced interface'), ('basic_customizations', 'Can change basic interface')),
                'default_permissions': (),
            },
        ),
    ]
