# Generated by Django 4.1.5 on 2023-10-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_customizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizer',
            old_name='navbar_options',
            new_name='navbar_fixed',
        ),
    ]
