# Generated by Django 4.1.5 on 2023-10-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_customizer', '0002_rename_navbar_options_customizer_navbar_fixed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizer',
            old_name='sidebar_vertical',
            new_name='sidebar_orientation',
        ),
    ]
