# Generated by Django 4.1.5 on 2023-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_customizer', '0005_alter_customizer_sidebar_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='main_theme',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
