# Generated by Django 4.1.5 on 2023-06-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicsoporte',
            name='codigo',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Código'),
        ),
    ]
