# Generated by Django 4.1.5 on 2023-09-10 22:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_remove_inventariobienes_ant_tipo_proc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0002_alter_solicsoporte_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicsoporte',
            name='updated',
        ),
        migrations.AddField(
            model_name='solicsoporte',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicsoporte',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicsoporte',
            name='descrip',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Código')),
                ('tipo_solicitud', models.CharField(choices=[('SDT', 'Solicitud de Distribución'), ('STL', 'Solicitud de Traslado'), ('SDC', 'Solicitud de Desincorporación')], max_length=25, verbose_name='Tipo de Solicitud')),
                ('prioridad', models.CharField(blank=True, choices=[('MB', 'Muy baja'), ('BJ', 'Baja'), ('NM', 'Normal'), ('AT', 'Alta'), ('MA', 'Muy alta')], default='NM', max_length=25, null=True, verbose_name='Prioridad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(blank=True, choices=[('ECR', 'En Creación'), ('PEN', 'Pendiente'), ('REC', 'Rechazada'), ('RES', 'Resuelta')], default='ECR', max_length=25, null=True, verbose_name='Estado de la Solicitud')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Solicitud')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_unidad_set', to='erp.unidad', verbose_name='Unidad Solicitante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de movimiento',
                'verbose_name_plural': 'Solicitudes de Movimientos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.inventariobienes', verbose_name='Inventario de Bienes')),
                ('productos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_productos_set', to='erp.producto', verbose_name='Productos')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_set', to='solicitudes.solicitudes', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle Solicitud de Movimiento',
                'verbose_name_plural': 'Detalle Solicitudes de Movimientos',
                'ordering': ['id'],
            },
        ),
    ]
