# Generated by Django 4.1.5 on 2023-09-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_detsolicitud_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='tipo_solicitud',
            field=models.CharField(choices=[('DIST', 'Solicitud de Distribución'), ('TRAS', 'Solicitud de Traslado'), ('DESINC', 'Solicitud de Desincorporación')], max_length=25),
        ),
    ]
