# Generated by Django 4.1.5 on 2023-09-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_remove_inventariobienes_ant_tipo_proc_and_more'),
        ('solicitudes', '0005_alter_solicitudes_tipo_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_departamento_set', to='erp.departamento'),
        ),
    ]
