# Generated by Django 4.1.5 on 2023-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitudes_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tipo_solicitud',
            field=models.CharField(choices=[('DIST', 'Solicitud de Distribución'), ('TRAS', 'Solicitud de Traslado'), ('DESINC', 'Solicitud de Desincorporación de Bienes en uso')], max_length=25),
        ),
    ]
