# Generated by Django 4.1.5 on 2023-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_solicitudes_tipo_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('MB', 'Muy baja'), ('BJ', 'Baja'), ('NM', 'Normal'), ('AL', 'Alta'), ('MA', 'Muy alta')], default='NM', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='solicsoporte',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('MB', 'Muy baja'), ('BJ', 'Baja'), ('NM', 'Normal'), ('AL', 'Alta'), ('MA', 'Muy alta')], max_length=2, null=True),
        ),
    ]
