# Generated by Django 4.1.5 on 2023-11-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_alter_controlstock_almacenes_and_more'),
        ('solicitudes', '0011_alter_solicitudes_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_concept_set', to='erp.concepmovimiento'),
        ),
    ]
