# Generated by Django 4.1.5 on 2023-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_solicitudes_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsolicitud',
            name='cantidad_aprobada',
            field=models.IntegerField(default=0),
        ),
    ]
