# Generated by Django 4.1.5 on 2023-11-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_detsolicitud_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsolicitud',
            name='aprobado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
