# Generated by Django 4.1.5 on 2023-11-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_remove_trasladoproduc_created_and_more'),
        ('solicitudes', '0016_alter_solicitudes_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='unidad',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_depart_set', to='erp.departamento'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='unidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_unidad_destino_set', to='erp.unidad'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='unidad_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_unidad_origen_set', to='erp.unidad'),
        ),
    ]
