# Generated by Django 4.1.5 on 2023-10-04 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0002_remove_notificacion_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_emisor',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_receptor',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_autor_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificacionUsuarioReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_set', to='notificaciones.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_receptor_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
