# Generated by Django 4.1.5 on 2023-10-07 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0003_remove_notificacion_leida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='autor',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='imagen',
            field=models.ImageField(blank=True, default='notificaciones/info.png', null=True, upload_to='notificaciones/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='NotificacionUsuarioReceptor',
        ),
        migrations.AddField(
            model_name='notificacionusuario',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_set', to='notificaciones.notificacion'),
        ),
        migrations.AddField(
            model_name='notificacionusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
