# Generated by Django 4.1.5 on 2023-10-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_notificacionusuario_remove_notificacion_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='imagen',
            field=models.ImageField(blank=True, default='notificaciones/info.png', null=True, upload_to='media/notificaciones/%Y/%m/%d'),
        ),
    ]
