# Generated by Django 4.1.5 on 2023-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_alter_notificacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='imagen',
            field=models.ImageField(blank=True, default='notificaciones/info.png', null=True, upload_to='notificaciones/%Y/%m/%d'),
        ),
    ]
