# Generated by Django 4.1.5 on 2023-10-01 20:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('En creación', 'en creacion'), ('Aprobada', 'aprobada'), ('Rechazada', 'rechazada')], default='Aprobada', max_length=25)),
                ('razon', models.TextField(blank=True, null=True)),
                ('operacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobacion_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestion de Aprobacion',
                'verbose_name_plural': 'Gestion de Aprovaciones',
                'ordering': ['-fecha'],
                'permissions': (('approve_movimientos', 'Can approve movimientos'), ('approve_solicitudes', 'Can approve solicitudes')),
                'default_permissions': (),
            },
        ),
    ]
