# Generated by Django 4.1.5 on 2023-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprobaciones', '0002_rename_razon_aprobaciones_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobaciones',
            name='codigo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
